spring.application.name=Personal-Finance-Coach
spring.datasource.url=jdbc:mysql://localhost:3306/FinanceCoachDB?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=vikkysql@1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
jwt.secret=9cb8d50605fba2f638b0ed880f8fc8820338d064221e6165b54dc30354cc0b72
openrouter.api.key=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
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.model=deepseek/deepseek-r1-0528:free
